### ISSUE TITLE
Error with host_var inventory - ValueError: dictionary has length 1; 2 is required

### ISSUE THREAD

**Issue by mattee6** [geerlingguy/temperature-monitor#27]
I now have installed on the master and one slave, but both have the result:

ansible-playbook -i config/inventory playbooks/remote-monitor/main.yml
ERROR! Unexpected Exception: dictionary update sequence element #0 has length 1; 2 is required
to see the full traceback, use -vvv

Verbrose mode gives:

```
ansible-playbook -i config/inventory playbooks/remote-monitor/main.yml -vvv
No config file found; using defaults
ERROR! Unexpected Exception: dictionary update sequence element #0 has length 1; 2 is required
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 132, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 98, in __init__
    self.parse_inventory(host_list)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 171, in parse_inventory
    self.get_host_vars(host)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 771, in get_host_vars
    return self._get_hostgroup_vars(host=host, group=None, new_pb_basedir=new_pb_basedir, return_results=return_results)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 845, in _get_hostgroup_vars
    group_results = self._variable_manager.add_host_vars_file(base_path, self._loader)
  File "/usr/local/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 596, in add_host_vars_file
    data = self._load_inventory_file(path, loader)
  File "/usr/local/lib/python2.7/dist-packages/ansible/vars/__init__.py", line 577, in _load_inventory_file
    rval.update(data)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

inventory file has:

```
[master]
192.168.1.77

[remotes]
192.168.1.79
```

host_var has 2 files

192.168.1.77

inside:

```
Master
```

192.168.1.79

inside:

```
Hall
```

Files will follow when I can ssh to the machine to copy them!!

**Comment by mattee6** [comment]
Files now attached.  Had to zip them....

[files.zip](https://github.com/geerlingguy/temperature-monitor/files/730855/files.zip)

I am pretty sure that the files are incorrectly formatted.  Any advice would be appreciated.

**Comment by geerlingguy** [comment]
@mattee6 - Ah, I see what you're saying now.

The files you place in `host_vars` are only to store values like:

```yaml
---
# Set an offset (e.g. "-2" or "0") to calibrate the thermometer.
local_temp_offset: "0"

# Set a unique ID for this sensor (e.g. 0 for first one, 1 for second).
local_sensor_id: 0
```

(That would be for the first one).

**Comment by geerlingguy** [comment]
The actual names for different sensors are configured manually after you have everything set up on the master Pi—if it's Express.js app is running, you can use a tool that works with APIs (like [HTTPRequester](https://addons.mozilla.org/en-US/firefox/addon/httprequester/) for Firefox, or [DHC Restlet Client](https://chrome.google.com/webstore/detail/dhc-restlet-client/aejoelaoggembcahagimdiliamlcdmfm) for Chrome), and send a request in the format specified under the [Express.js app's API documentation](https://github.com/geerlingguy/temperature-monitor#dashboard-api) in the README file.

On a related note, I hope to make this process more intuitive in the future through a UI for adding/removing sensors: https://github.com/geerlingguy/temperature-monitor/issues/28

**Comment by mattee6** [comment]
Ok, that has stopped now.

I take it I run the ansible-playbook -i config/inventory                                                                                       playbooks/remote-monitor/main.yml

line from the master?

Below is a display of what I get....

```
sudo ansible-playbook -i config/inventory                                                                                       playbooks/remote-monitor/main.yml
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and
make sure become_method is 'sudo' (default).
This feature will be removed in a
future release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

PLAY [remotes] *****************************************************************

TASK [setup] *******************************************************************
The authenticity of host '192.168.1.79 (192.168.1.79)' can't be established.
ECDSA key fingerprint is KEY HERE.
Are you sure you want to continue connecting (yes/no)? yes
fatal: [192.168.1.79]: UNREACHABLE! => {"changed": false, "msg": "Failed to conn                                                                                        ect to the host via ssh: Warning: Permanently added '192.168.1.79' (ECDSA) to th                                                                                        e list of known hosts.\r\nPermission denied (publickey,password).\r\n", "unreach                                                                                        able": true}
        to retry, use: --limit @/home/pi/temperature-monitor/playbooks/remote-mo                                                                                        nitor/main.retry

PLAY RECAP *********************************************************************
192.168.1.79               : ok=0    changed=0    unreachable=1    failed=0
```

Any ideas???

**Comment by geerlingguy** [comment]
In the case above—it looks like the message ("Failed to conn...") was cut off by the terminal width. Can you see what else it's saying?

Also, maybe try connecting manually (`ssh pi@192.168.1.79`) and see what it says.

**Comment by mattee6** [comment]
On my git screen the full message is show if you scroll across:

The authenticity of host '192.168.1.79 (192.168.1.79)' can't be established.
ECDSA key fingerprint is KEY HERE.
Are you sure you want to continue connecting (yes/no)? yes
fatal: [192.168.1.79]: UNREACHABLE! => {"changed": false, "msg": "Failed to conn                                                                                        ect to the host via ssh: Warning: Permanently added '192.168.1.79' (ECDSA) to th                                                                                        e list of known hosts.\r\nPermission denied (publickey,password).\r\n", "unreach                                                                                        able": true}
        to retry, use: --limit @/home/pi/temperature-monitor/playbooks/remote-mo                                                                                        nitor/main.retry

I have ssh to that ip address from master, and all is fine.

**Comment by geerlingguy** [comment]
```
Permission denied (publickey,password).
```

That means Ansible is still having trouble connecting. Can you run the command `ansible -i config/inventory all -m ping` ?

That should try to connect to all hosts defined in the inventory. Maybe you also need to add user=pi or something like that (it might try to connect as your mac or windows username by default instead of pi, and I presume you're using the pi account on the Raspberry Pi and didn't configure a separate one).

**Comment by Paul-Dylan-Clark** [comment]
I had this too.  I resolved it by;
ssh-keygen -t ecdsa
then
ssh-copy-id 'username'@localhost
