### ISSUE TITLE
Can anyone help!

### ISSUE THREAD

**Issue by Paul-Dylan-Clark** [geerlingguy/temperature-monitor#30]
I've come across this promising app from Jeff which would be very useful for my project.

Unfortunately, I'm not a Linux or programmer guy.  My own specialties lie in Microsoft server, so please forgive me!

Basically, I have a PI zero with an ADC board and I can read the voltages;
 
![image](https://user-images.githubusercontent.com/29160930/26926858-413c6564-4c47-11e7-8542-9a7dc18ec894.png)

I want to be able to graph these voltages just like the temperature in Jeff's program.

But I'm having issues!  Firstly, I've tried setting up a VirtualBox Debian to load the Master program which the PI Zero can log to and I can't get it to work.  I managed to install Ansible, SSH, Sudo and install the keys (ecdsa, dsa etc), modified the /config/config.yml and inventory to suit.

I can;
    log onto SSH
    Ansible 'Ping'
    log onto Mysql
    run as Sudo
Without error.

I ran the Ansible installer for the master program which only came up with one error (modifying /boot/config.txt) which I don't think is too important for the VM.

Logging onto http:\\localhost:3000 comes up with nothing.

I've hit the limits of my diagnostic capabilities of this new OS (to me) and I don't know where to turn to next.

Any help would be greatly appreciated.

**Comment by geerlingguy** [comment]
You don't necessarily need to have VirtualBox / VMs running to use this app; you can install it directly on the Rasbperry Pi itself. The VM setup process is really only used for my own local testing.
