### ISSUE TITLE
Arduino image left over

### ISSUE THREAD

**Issue by mi-hol** [geerlingguy/temperature-monitor#37]
Appreciate your great work! 
I got a bit confused by https://github.com/geerlingguy/temperature-monitor/blob/master/images/arudino-temperature-wiring.jpg it seems a left over from earlier project setup including Arduino devices but the PR below removed the requirement for it to exist in the repo. Maybe you wanted to delete it?
https://github.com/geerlingguy/temperature-monitor/commit/9a7a1a213ee0085247939d1834e7fc6717d599b7

**Comment by geerlingguy** [comment]
Good point; I should drop that image as it's no longer necessary.
